# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/zh"
  
  title = "关永吉个人学术主页"
  
  [zh.params]
  description = "欢迎访问关永吉的个人学术主页"
  email = "yongji.guan@outlook.com"
  phone = "+86-18809463920"
  address = " 甘肃省兰州市天水南路222号兰州大学飞云楼401室"
  office_hours = """工作日 09:00 到 12:00<br>
                  和 14:00 到 18:00"""
  latitude = "36.04915"
  longitude = "103.85614"
  
  [[zh.menu.main]]
  name = "个人简介"
  url = "#about"
  weight = 10

  [[zh.menu.main]]
  name = "发表论文"
  url = "#featured"
  weight = 20

  [[zh.menu.main]]
  name = "学术报告"
  url = "#talks"
  weight = 30

[[zh.menu.main]]
  name = "教学课程"
  url = "#teaching"
  weight = 40

[[zh.menu.main]]
  name = "科研课题"
  url = "#projects"
  weight = 50

[[zh.menu.main]]
  name = "学术新闻"
  url = "#posts"
  weight = 60

[[zh.menu.main]]
  name = "常用链接"
  url = "#links"
  weight = 70

[[zh.menu.main]]
  name = "联系方式"
  url = "#contact"
  weight = 80
